<a href="https://colab.research.google.com/github/nisha432/facial-recognition-/blob/main/Copy_of_project5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Project Name**    -

**DeepFER: Facial Emotion Recognition Using Deep Learning**

##### **Project Type**    -
##### **Contribution**    -Team
##### **Team Member 1 -**-PrabhaKar Harijan
##### **Team Member 2 -**-Nisha Ahire


# **Project Summary -**

Emotion recognition is crucial for enhancing user experiences in various digital domains, including mental health, human-computer interaction, customer service, and security. However, accurately recognizing emotions from facial expressions remains a challenging task due to variability in facial features, environmental conditions, and the need for real-time processing. Traditional emotion recognition methods, relying on handcrafted features and rule-based approaches, lack adaptability and generalizability, struggling to identify subtle emotional expressions across different demographics and settings.

Recent advancements in deep learning, particularly Convolutional Neural Networks (CNNs) and Transfer Learning, offer a promising solution. By leveraging these techniques, it is possible to develop more robust and adaptable emotion recognition systems. However, creating a high-performing model requires addressing complex challenges, including dataset diversity and annotation accuracy, generalization and robustness across varying lighting, backgrounds, and facial features, real-time processing efficiency, and practical application and usability.

Due to RAM and GPU constraints, we utilized a subset of the dataset, consisting of 1000 images per folder. While this limitation may impact the model's accuracy, our preliminary results demonstrate the model's potential. It is essential to note that the predicted output may vary due to the limited training data, and the model's performance will improve with additional training data.

Despite these limitations, our model demonstrates promising results. The model accurately predicts emotions with reasonable accuracy, and real-time processing efficiency is achieved. To further enhance the model's performance, we plan to increase the dataset size to improve accuracy, explore data augmentation techniques to diversify the training data, and optimize model architecture for improved generalization.

Our deep learning-based emotion recognition system demonstrates potential despite limitations. With additional training data and optimization, we expect significant improvements in accuracy and generalization. This project paves the way for more intuitive and empathetic interactions between humans and machines. By developing an efficient and adaptable emotion recognition system, we can enhance user experiences in various digital domains.

The key objectives of this project include developing a deep learning-based emotion recognition system, achieving accurate emotion recognition, enhancing generalization across diverse demographics and settings, ensuring real-time processing efficiency, and integrating seamlessly into dynamic and interactive applications. While we have made progress, ongoing development and refinement are necessary to achieve optimal results.

# **GitHub Link -**

https://github.com/nisha432/facial-recognition-

# **Problem Statement**


Emotional intelligence in machines is becoming increasingly essential for applications across various fields, including healthcare, human-computer interaction, and security. Accurately recognizing human emotions from facial expressions, known as Facial Emotion Recognition (FER), is a challenging task due to the complexity of facial muscle movements, variations in lighting, occlusions, and individual differences in expression.

Traditional FER systems often rely on handcrafted features and classical machine learning algorithms, which can be limited in handling diverse and large datasets. These systems tend to struggle with generalizing across different demographic groups and fail to capture subtle nuances in expressions. As such, there is a pressing need for more robust and scalable FER systems that can perform reliably in real-world scenarios.

The advancement in deep learning provides a promising pathway to address these limitations. DeepFER aims to leverage deep learning architectures, such as convolutional neural networks (CNNs) and recurrent neural networks (RNNs), to build a high-performance FER model capable of accurately identifying emotions from facial expressions in various conditions. This project will explore different deep learning techniques to optimize the performance of FER, focusing on improving accuracy, speed, and generalizability across diverse environments and populations.

The objective of this study is to design and implement a deep learning-based FER model that not only achieves high accuracy but also addresses issues of generalization, robustness, and efficiency, thus paving the way for broader applications in human-computer interaction, mental health diagnostics, and beyond.

# **General Guidelines** : -  

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 15 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]





6. You may add more ml algorithms for model creation. Make sure for each and every algorithm, the following format should be answered.


*   Explain the ML Model used and it's performance using Evaluation metric Score Chart.


*   Cross- Validation & Hyperparameter Tuning

*   Have you seen any improvement? Note down the improvement with updates Evaluation metric Score Chart.

*   Explain each evaluation metric's indication towards business and the business impact pf the ML model used.




















# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries

In [ ]:
# Import Libraries

In [ ]:
# importing the dependencies
from zipfile import ZipFile
import os
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from zipfile import ZipFile
import os
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import classification_report
import tensorflow as tf
from tensorflow import keras

### Dataset Loading

In [ ]:
# Load Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# extracting the compress folder
from zipfile import ZipFile
file_name= "/content/drive/MyDrive/AlmaBetter/datasets/Face Emotion Recognition Dataset.zip"

with ZipFile(file_name,'r') as zip:
  zip.extractall()
  print("File is extracted")

File is extracted


In [ ]:
angry =  os.listdir(r'/content/images/train/angry')
disgust =  os.listdir(r'/content/images/train/disgust')
fear =  os.listdir(r'/content/images/train/fear')
happy =  os.listdir(r'/content/images/train/happy')
neutral =  os.listdir(r'/content/images/train/neutral')
sad =  os.listdir(r'/content/images/train/sad')
surprise =  os.listdir(r'/content/images/train/surprise')


In [ ]:
# List of paths for each emotion category
faces = [
    (r'/content/images/train/angry', 0),
    (r'/content/images/train/disgust', 1),
    (r'/content/images/train/fear', 2),
    (r'/content/images/train/happy', 3),
    (r'/content/images/train/neutral', 4),
    (r'/content/images/train/sad', 5),
    (r'/content/images/train/surprise', 6)
]

data = []
labels = []
max_images_per_folder = 1000  # Limit to 1000 images per folder

we have used 1000 images per folder because of RAM and GPU contraint .

In [ ]:
# Load images and labels
for path, label in faces:
    if os.path.exists(path):  # Check if the path exists
        count = 0  # Counter for the number of images loaded from the folder
        for img_file in os.listdir(path):
            if count >= max_images_per_folder:
                break  # Stop if limit is reached

            img_path = os.path.join(path, img_file)
            image = Image.open(img_path)
            image = image.resize((122, 122))
            image = image.convert('RGB')
            image = np.array(image)
            data.append(image)
            labels.append(label)

            count += 1

This loop appears to be loading and preprocessing images from each emotion category folder, resizing them to 122x122, converting to RGB, and storing them in the data and labels lists, while limiting the number of images per folder to 1000.

In [ ]:
# Convert to numpy arrays
x = np.array(data)
y = np.array(labels)

# Cross-validation
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=0)
accuracy_per_fold, precision_per_fold, recall_per_fold, f1_per_fold = [], [], [], []

for train_idx, val_idx in kfold.split(x, y):
    x_train, x_val = x[train_idx] / 255.0, x[val_idx] / 255.0
    y_train, y_val = y[train_idx], y[val_idx]

    # Define the CNN model
# Build the convolutional neural network
    num_classes = len(set(labels))  # Dynamic number of classes based on labels
    model = keras.Sequential([
        keras.layers.Input(shape=(122, 122, 3)),  # Specify input shape here
        keras.layers.Conv2D(32, kernel_size=(3, 3), activation='relu'),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Conv2D(64, kernel_size=(3, 3), activation='relu'),
        keras.layers.MaxPooling2D(pool_size=(2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(64, activation='relu'),
        keras.layers.Dense(num_classes, activation='softmax')
    ])


1. This section:

---



Converts data and labels to NumPy arrays.

Defines a stratified k-fold cross-validation object.

Iterates through each fold, normalizing pixel values and splitting data into training and validation sets.

Defines a convolutional neural network (CNN) model using Keras Sequential API.

2. The CNN architecture consists of:

---



Input layer with shape (122, 122, 3)

Three convolutional blocks with max-pooling

Flatten layer

Two dense layers (64 units with ReLU activation and num_classes units with softmax activation)

In [ ]:
# Compile and train
model.compile(optimizer='Adamax', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, validation_data=(x_val, y_val), epochs=30)

Epoch 1/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 149s 914ms/step - accuracy: 0.1804 - loss: 1.9298 - val_accuracy: 0.2238 - val_loss: 1.8685
Epoch 2/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 191s 847ms/step - accuracy: 0.2543 - loss: 1.8398 - val_accuracy: 0.2595 - val_loss: 1.8027
Epoch 3/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 146s 873ms/step - accuracy: 0.3190 - loss: 1.7140 - val_accuracy: 0.3279 - val_loss: 1.7217
Epoch 4/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 136s 836ms/step - accuracy: 0.3686 - loss: 1.6298 - val_accuracy: 0.3248 - val_loss: 1.7092
Epoch 5/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 145s 856ms/step - accuracy: 0.4089 - loss: 1.5440 - val_accuracy: 0.3652 - val_loss: 1.6594
Epoch 6/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 146s 879ms/step - accuracy: 0.4550 - loss: 1.4700 - val_accuracy: 0.3675 - val_loss: 1.6610
Epoch 7/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 152s 945ms/step - accuracy: 0.5025 - loss: 1.3505 - val_accuracy: 0.3551 - val_loss: 1.6424
Epoch 8/30
161/161 ━━━━━━━━━━━━━━━━━━━━ 199s 924ms/step - accuracy: 0.5324 -

Compilation and training configuration:
Optimizer: Adamax (a variant of Adam optimizer)
Loss function: Sparse categorical cross-entropy (suitable for multi-class classification with integer labels)
Metric: Accuracy
Training configuration:
Training data: x_train, y_train
Validation data: x_val, y_val
Number of epochs: 30

In [ ]:
# Evaluate the fold
y_val_pred = np.argmax(model.predict(x_val), axis=1)
report = classification_report(y_val, y_val_pred, output_dict=True, zero_division=0)


41/41 ━━━━━━━━━━━━━━━━━━━━ 10s 246ms/step


In [ ]:
# Save metrics for each fold
accuracy_per_fold.append(report['accuracy'])
precision_per_fold.append(report['weighted avg']['precision'])
recall_per_fold.append(report['weighted avg']['recall'])
f1_per_fold.append(report['weighted avg']['f1-score'])

Evaluating model performance using classification report:
Predicting classes for validation set
Generating classification report with weighted average metrics
Extracting accuracy, precision, recall, and F1-score for each fold

In [ ]:
# Final Evaluation on Test Set
x_train, x_test, y_train, y_test = train_test_split(x / 255.0, y, test_size=0.2, random_state=0)
model.fit(x_train, y_train, validation_split=0.1, epochs=30)
y_test_pred = np.argmax(model.predict(x_test), axis=1)
print("Final Model Evaluation on Test Set:")
print(classification_report(y_test, y_test_pred, zero_division=0))

Epoch 1/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 116s 796ms/step - accuracy: 0.8254 - loss: 1.0949 - val_accuracy: 0.8583 - val_loss: 0.6240
Epoch 2/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 162s 939ms/step - accuracy: 0.9010 - loss: 0.4106 - val_accuracy: 0.8602 - val_loss: 0.6266
Epoch 3/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 127s 838ms/step - accuracy: 0.9329 - loss: 0.2651 - val_accuracy: 0.8466 - val_loss: 0.6564
Epoch 4/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 144s 846ms/step - accuracy: 0.9655 - loss: 0.1605 - val_accuracy: 0.8350 - val_loss: 0.7083
Epoch 5/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 135s 804ms/step - accuracy: 0.9800 - loss: 0.1081 - val_accuracy: 0.8447 - val_loss: 0.7892
Epoch 6/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 119s 822ms/step - accuracy: 0.9875 - loss: 0.0722 - val_accuracy: 0.8447 - val_loss: 0.7917
Epoch 7/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 145s 837ms/step - accuracy: 0.9944 - loss: 0.0388 - val_accuracy: 0.8524 - val_loss: 0.8439
Epoch 8/30
145/145 ━━━━━━━━━━━━━━━━━━━━ 141s 836ms/step - accuracy: 0.9955 -

1. Final evaluation on test set:

---



Splits data into training and testing sets (80% for training, 20% for testing)

Normalizes pixel values (x / 255.0)

Trains model on training set with validation split (10% of training set)

Predicts classes for test set

Prints classification report for final model evaluation on test set





In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

# ...

y_test_pred = np.argmax(model.predict(x_test), axis=1)

print("Final Model Evaluation on Test Set:")
print(classification_report(y_test, y_test_pred, zero_division=0))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))
print(f"Test Accuracy: {accuracy_score(y_test, y_test_pred):.4f}")



41/41 ━━━━━━━━━━━━━━━━━━━━ 11s 279ms/step
Final Model Evaluation on Test Set:
              precision    recall  f1-score   support

           0       0.81      0.84      0.82       201
           1       0.80      0.90      0.85        77
           2       0.75      0.63      0.68       198
           3       0.86      0.84      0.85       211
           4       0.73      0.81      0.77       198
           5       0.77      0.76      0.77       221
           6       0.86      0.87      0.87       182

    accuracy                           0.80      1288
   macro avg       0.80      0.81      0.80      1288
weighted avg       0.80      0.80      0.80      1288

Confusion Matrix:
[[168   3   5   2   9  12   2]
 [  3  69   2   0   1   2   0]
 [ 13   5 125  11  12  17  15]
 [  2   1   7 178  15   4   4]
 [  8   1   7   8 161  10   3]
 [  9   5  14   7  17 168   1]
 [  4   2   7   1   6   4 158]]
Test Accuracy: 0.7974


In [ ]:

# Save the model
model.save("emotion_model.keras")


Predicting system

In [ ]:
import numpy as np
from tensorflow.keras.models import load_model
from PIL import Image
import cv2

# Load the trained model
model = load_model("/content/emotion_model.keras")

# Define emotion labels
emotion_labels = {0: "Angry", 1: "Disgust", 2: "Fear", 3: "Happy", 4: "Neutral", 5: "Sad", 6: "Surprise"}

def preprocess_image(image_path):
    """
    Preprocess the image to be compatible with the model input.
    Resizes the image to 122x122, converts it to RGB, and scales pixel values.
    """
    image = Image.open(image_path)
    image = image.resize((122, 122))
    image = image.convert('RGB')
    image = np.array(image) / 255.0  # Scale pixel values
    return np.expand_dims(image, axis=0)  # Add batch dimension

def predict_emotion(image_path):
    """
    Predicts the emotion from an image using the trained model.
    """
    processed_image = preprocess_image(image_path)
    predictions = model.predict(processed_image)
    emotion_index = np.argmax(predictions)  # Get the index of the highest probability
    emotion_label = emotion_labels[emotion_index]  # Map to the emotion label
    confidence = np.max(predictions)  # Confidence level for the predicted class
    return emotion_label, confidence


1. Loaded trained Keras model using load_model.

2. Defined emotion labels dictionary for mapping indices to labels.

3. Implemented preprocess_image function:

---



Resizes image to 122x122.

Converts image to RGB.

Scales pixel values between 0 and 1.

Adds batch dimension.

4. Implemented predict_emotion function:

---



Calls preprocess_image.

Makes prediction using trained model.

Extracts emotion label and confidence level.

In [ ]:
# Example usage
image_path = r"/content/images/validation/happy/10096.jpg"  # Path to the image you want to predict
emotion, confidence = predict_emotion(image_path)
print(f"Predicted Emotion: {emotion}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Predicted Emotion: Happy


it is predicting and our model is working.

However  accuracy will be low  Due to less data training it might affect the output.

# **Conclusion**

The completion of this machine learning capstone project represents a significant milestone in developing a robust emotion recognition system based on facial expressions. Through the implementation of convolutional neural networks (CNNs), we were able to effectively classify emotions from images, utilizing data augmentation techniques to enhance model performance and generalization capabilities.

The training process demonstrated a variety of outcomes, with the model showing improvement in accuracy over the epochs, despite initial challenges with overfitting and varying loss values. The training metrics indicated a mean accuracy of approximately 40%, alongside precision, recall, and F1-scores that reflect a foundation for further improvement.

To summarize key achievements:

A trained model capable of predicting emotions from facial images was successfully developed and validated.
Data augmentation was effectively integrated to enrich the training dataset, providing the model with exposure to a wider variety of scenarios.
Final evaluation metrics demonstrated potential areas for further optimization and tuning of hyperparameters.
Moving forward, it will be beneficial to explore advanced techniques such as transfer learning, fine-tuning on larger datasets, or implementing more sophisticated architectures, which could enhance the model's predictive power and overall reliability. This foundational work lays the groundwork for future enhancements and practical applications in real-world scenarios, such as human-computer interaction, emotional AI, and mental health monitoring systems.

### ***Hurrah! You have successfully completed your Machine Learning Capstone Project !!!***